// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/PhanBaThien/Fish-Game/Fish-Back-End/internal/repository"
	"github.com/PhanBaThien/Fish-Game/Fish-Back-End/internal/transport/http"
	"github.com/PhanBaThien/Fish-Game/Fish-Back-End/internal/usecase"
	"github.com/PhanBaThien/Fish-Game/Fish-Back-End/internal/ws"
	"github.com/PhanBaThien/Fish-Game/Fish-Back-End/pkg/utils"
	"github.com/jackc/pgx/v5/pgxpool"
)

func InitializeApp(db *pgxpool.Pool, hasher utils.PasswordHasher, tokenMaker utils.TokenMaker) (http.Handlers, error) {
	userRepository := repository.NewUserRepository(db)
	refreshTokenRepository := repository.NewRefreshTokenRepository(db)
	walletRepository := repository.NewWalletRepository(db)
	authUsecase := usecase.NewAuthUsecase(userRepository, refreshTokenRepository, walletRepository, hasher, tokenMaker)
	authHandler := http.NewAuthHandler(authUsecase, tokenMaker)

	roomRepository := repository.NewRoomRepository(db)
	roomUsecase := usecase.NewRoomUsecase(roomRepository)
	roomHandler := http.NewRoomHandler(roomUsecase, tokenMaker)

	fishRepository := repository.NewFishRepository(db)
	fishUsecase := usecase.NewFishUsecase(fishRepository)
	fishHandler := http.NewFishHandler(fishUsecase, tokenMaker)

	walletUsecase := usecase.NewWalletUsecase(walletRepository)
	walletHandler := http.NewWalletHandler(walletUsecase, tokenMaker)

	hub := ws.NewHub()
	wsHandler := http.NewWSHandler(hub, walletUsecase, roomUsecase, fishUsecase, tokenMaker)

	handlers := http.Handlers{
		Auth:   authHandler,
		Room:   roomHandler,
		Fish:   fishHandler,
		Wallet: walletHandler,
		WS:     wsHandler,
	}
	return handlers, nil
}
