// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/PhanBaThien/Fish-Game/Fish-Back-End/internal/repository"
	"github.com/PhanBaThien/Fish-Game/Fish-Back-End/internal/transport/http"
	"github.com/PhanBaThien/Fish-Game/Fish-Back-End/internal/usecase"
	"github.com/PhanBaThien/Fish-Game/Fish-Back-End/pkg/utils"
	"github.com/jackc/pgx/v5/pgxpool"
)

// Injectors from wire.go:

// InitializeApp là hàm mẫu, Wire sẽ đọc hàm này và đẻ ra code thật
func InitializeApp(db *pgxpool.Pool, hasher utils.PasswordHasher, tokenMaker utils.TokenMaker) (http.Handlers, error) {
	userRepository := repository.NewUserRepository(db)
	authUsecase := usecase.NewAuthUsecase(userRepository, hasher, tokenMaker)
	authHandler := http.NewAuthHandler(authUsecase, tokenMaker)
	handlers := http.Handlers{
		Auth: authHandler,
	}
	return handlers, nil
}
