// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Role struct {
	ID       int32
	RoleName string
}

type User struct {
	ID        int64
	Username  string
	Email     string
	Password  string
	RoleID    int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
